version: '3.8'

services:
  backend:
    build: .
    image: stand-with-dorayaki-backend-img
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
       